env:
  node: true

extends:
  - 'eslint:recommended'
parserOptions:
  sourceType: module
  allowImportExportEverywhere: false
  codeFrame: false
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
